### PR TITLE
Packaging and clean up

### PR DESCRIPTION
**Pull request by ehsteve**
This PR makes use of the sunpy package template to move everything into a fully featured python package which includes automatic testing as well as docs.

### CODE REVIEW

**Comment by ehsteve** [comment]
Once this is accepted, please create an account on [travis](https://travis-ci.org) and hook up for automatic testing. You can run testing locally with `python setup.py test`. This will fail right now because of the old `hapi_test_old.py` file which I did not delete. Those codes need to be incorporated into `test_hapi.py`. Please also create an account on [readthedocs](http://readthedocs.org) to enable automatic creation of your documentation.

**Comment by ehsteve** [comment]
More information about those steps available on the [sunpy template documentation](https://docs.sunpy.org/projects/package-template/en/latest/nextsteps.html) currently hosted on readthedocs! Let me know if you have any questions.

**Comment by rweigel** [comment]
Thanks! I'll work on this soon.

**Comment by ehsteve** [comment]
@rweigel I can work on fixing the tests if you want. There is a little tricky bit when testing that requires a remote server.

**Comment by rweigel** [comment]
Thanks again for your contributions.

Regarding the packaging, my preference would be to have a subdirectory containing all of the sunpy-specific packaging stuff and to keep the top-level about the same.

Here is a suggested layout:

```
README.md # Current README, not SunPy README. Please add instructions for installing using package method once complete
hapi.py (now has hapiplot.py and dateticks.py moved into it)
hapi_demo.py (same as current)
test/
  test.py (tests functions in hapi.py)
  test-sunpy.py (test sunpy packaging only)
misc/ (stuff for testing and experimentation, etc.; not to be included in sunpy package)
sunpy/ (All of the packaging stuff and sunpy.sh)
  sunpy.sh (script to build sunpy package - copy hapi.py to sunpy/, push package, etc.)
```

What is the lint program and switches that you used? I'll do that as a separate commit.

I'll work on the unit tests later. The tests that I have now were mostly for spot-checking new code and I need to put some thought into what checks should be run for Travis. The code uses a test data server that may go down, so I think it may be better to have Travis actually create the test server locally by 

```
# TODO: Change this to a tagged version for consistency
git clone https://github.com/hapi-server/server-nodejs
npm start
```
For the tests, for now, I suggest just creating a stub program that simply does something like
```
import hapi from hapi
Servers = hapi()
if len(Servers) > 0:
  exit 1
else:
 exit 0
```

When I have used Travis before with nodejs programs, I used npm install; npm test and these commands used package.json. It seems that the equivalent is requirements.txt. Have you had experience with this? The one complication that I see is that we'll want to test against Python 2.7 and 3.6+ packages.

**Comment by ehsteve** [comment]
Forgot to say that this packaging locks you into to Python >3.5. I don't think it is worth releasing packages for 2.7 anymore has all major packages have already made the move and many have promised to migrate.

**Comment by rweigel** [comment]
Locking into 3.6 should not be an issue for the sunpy package.

**Comment by ehsteve** [comment]
@rweigel I'm not sure I understand your concerns about the structure. This is using the standard python packaging structure and is not a SunPy standard. No code should live in the root directory. You can see a Python package template [here](https://github.com/audreyr/cookiecutter-pypackage). No code should live in the root directory so hapy.py should not live there. I also don't understand why you mention a sunpy directory as your project is not related to sunpy. I'm just using the sunpy package template as a convenience as it is consistent with many of our standards. I'd be happy to have a telecon with you to discuss this as it may be easier.

**Comment by ehsteve** [comment]
Also for the linting, I just used the standard `pylint`program.

**Pull request closed without merging**
